folder.features = ESIGNATURE,INDEXING,AISEARCH
document.features = ESIGNATURE,INDEXING,BLOCKCHAIN
author.features = ESIGNATURE,INDEXING,AISEARCH
reviewer.features = ESIGNATURE,INDEXING,AISEARCH
template.features = ESIGNATURE,INDEXING,AISEARCH
lmscategory.features = ESIGNATURE,INDEXING,AISEARCH