# ==============================================
# RabbitMQ Common Connection Settings
# ==============================================
spring.rabbitmq.host = 127.0.0.1
spring.rabbitmq.port = 5672
spring.rabbitmq.username = guest
spring.rabbitmq.password = guest
spring.rabbitmq.virtual-host = /
spring.rabbitmq.connection-timeout = 60000

spring.rabbitmq.publisher-confirm-type = correlated
spring.rabbitmq.publisher-returns = true

outbox.dispatch.interval = 2000

# ==============================================
# Workflow Messaging
# ==============================================
rabbitmq.exchange.workflow.command = workflow.command.exchange
rabbitmq.exchange.workflow.event = workflow.event.exchange
rabbitmq.exchange.workflow.ack = workflow.ack.exchange
rabbitmq.exchange.workflow.dlx = workflow.dlx

rabbitmq.queue.workflow.command = workflow.command.queue
rabbitmq.queue.workflow.ack = workflow.ack.queue
rabbitmq.queue.workflow.dlq = workflow.dlq

rabbitmq.routing.workflow.command.prefix = workflow.command
rabbitmq.routing.workflow.event.prefix = workflow.event
rabbitmq.routing.workflow.ack.prefix = workflow.ack

# ==============================================
# Planning / Saga Messaging
# ==============================================
rabbitmq.exchange.planning.command = planning.command.exchange
rabbitmq.routing.planning.command.prefix = planning.command

rabbitmq.exchange.saga.command = saga.command.exchange
rabbitmq.routing.saga.command.prefix = saga.command

rabbitmq.queue.saga.command = saga.command.queue
rabbitmq.queue.planning.reply = planning.reply.q
