# ==============================================
# Workflow Entities Configuration
# ==============================================
workflow.entities = customercomplaint, \
					rollorder, \
					maintenance, \
					machine, \
					machinedie, \
					order, \
					precutorder, \
					resourcesbooking, \
					correctiveactionrequest, \
					change, \
					rca

# ==============================================
# Customer Complaint Workflow
# ==============================================
workflow.customercomplaint.actions = start_workflow, \
										maker_approve
workflow.customercomplaint.start_workflow.steps = status, \
													assignment, \
													notification
workflow.customercomplaint.start_workflow.state = DRAFT
workflow.customercomplaint.start_workflow.action-type = start_workflow
workflow.customercomplaint.start_workflow.workflow-step = start_workflow
workflow.customercomplaint.start_workflow.role = author
workflow.customercomplaint.start_workflow.notification-message = Workflow started for customer complaint

workflow.customercomplaint.maker_approve.steps = status, \
													assignment, \
													notification
workflow.customercomplaint.maker_approve.state = SUBMITTED
workflow.customercomplaint.maker_approve.action-type = maker_approve
workflow.customercomplaint.maker_approve.workflow-step = maker_approve
workflow.customercomplaint.maker_approve.role = reviewer
workflow.customercomplaint.maker_approve.notification-message = Customer complaint record been approved by author
