# ==============================================
# Workflow Entities Configuration
# ==============================================
workflow.entities = customercomplaint, \
					rollorder, \
					maintenance, \
					machine, \
					machinedie, \
					order, \
					precutorder, \
					resourcesbooking, \
					correctiveactionrequest, \
					change, \
					rca

# ==============================================
# Customer Complaint Workflow
# ==============================================
workflow.customercomplaint.actions = start_workflow
workflow.customercomplaint.start_workflow.steps = status, \
													assignment, \
													notification
